= Faya front-end

Faya provides a simple way to create and manage tokens through its web interface or its API.

NOTE: This repository only contains the front-end part of Faya.

== Configuration

.Environment variables
[options="header"]
|===
|Name |Default |Description

|API_URL
|http://localhost:3000
|Full URL of the Faya API

|PORT
|8080
|Define the port on which to run Faya front-end server

|HTTPS_ENABLED
|null
|(in prod mode only) Set to true if Faya front-end is behind a reverse proxy providing HTTPS
|===

== Environments

Run this command to start the application in dev mode :

    npm start

Run these commands to start the application in prod mode :

    npm run build
    node server.js

== Docker

The application can be started either in dev mode or production mode in a Docker container (default to prod env).

To start the application in dev mode, run a container with the environment variable "PROD" set to false. Don't forget to mount src/ folder in the container if you want hot reloading.

== References

The webpack configuration is based on https://github.com/preboot/angular2-webpack[preboot/angular2-webpack]